### ISSUE TITLE
Can't add to the budgie panel

### ISSUE THREAD

**Issue by DrunkenAlcoholic** [shymmq/budgie-script-applet#7]
Hi, im having problems adding this to the budgie panel, it shows in the list of applet to add but clicking "add" doesn't actually add it to the panel, so no settings ect. displayed, maybe I miss understanding the how to get this installed correctly?

**Comment by WinnerWind** [comment]
Hi there! I +1 this. What's going on? This is a really cool applet and I would love to use it.

**Comment by szwsck** [comment]
Hi, unfortunately I haven't had Budgie installed for a few years now, so I can't test or fix it (PRs/forks are welcome). You could try to launch `script.py` from console and see if any errors show up.

**Comment by WinnerWind** [comment]
Oh! It's quite a shame, but I understand : Everyone gets busy sometimes

I installed this applet from the AUR, however upon trying the script.py from the git, I get this error.
```
>>> python -m script.py 
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/soham/aur/budgie-script-applet/script.py", line 4, in <module>
    import settings
  File "/home/soham/aur/budgie-script-applet/settings.py", line 1, in <module>
    from appdirs import AppDirs
ModuleNotFoundError: No module named 'appdirs'
```
I have checked that I have PythonGOObject. I already have that when I was running the script. Also, the plugin was run from within `~/.local/share/budgie-desktop/plugins`

Edit : Should clarify : the above test was not run from within the above mentioned directory but running it in the above mentioned directory throws the same error.

**Comment by szwsck** [comment]
`appdirs` module is not installed on your system but it seems like [it has been deprecated](https://github.com/ActiveState/appdirs) anyway. I've replaced it with `platformdirs`, wchich you'll need to install with `pip install platformdirs`.

**Comment by szwsck** [comment]
By the way, can you link to the AUR package you mentioned? I don't remember submitting it to AUR, and I can't find the package either.

**Comment by WinnerWind** [comment]
Weird, I can't find the package either. Maybe it was taken down..? Or I just misremembered.

I already have `python-platformdirs` installed via Pacman. 

The fix works. Thank you!
![image](https://github.com/szwsck/budgie-script-applet/assets/71366717/29a387d3-3380-465d-937a-6c62483607de)


I'll just have to add it to a panel and i'll let you know how it goes. I can't do any indepth testing right now, sorry.

**Comment by WinnerWind** [comment]
Hi there! Did some testing with a polybar script I found
I'm happy to say that it does work! Though, my panel crashed after tweaking the command a bit, maybe it's the script itself.

![image](https://github.com/szwsck/budgie-script-applet/assets/71366717/e30e7847-c8e3-42a3-818a-622b126a8f36)

The only problem is that the polybar script I use is supposed to have buttons, which don't appear, but I guess that could also be the script itself's fault. [I used this one](https://github.com/PrayagS/polybar-spotify?tab=readme-ov-file)

Anyway, glad to see that this applet works again. Looking forward to seeing a whole new world of possibilities using this simple applet. Thanks!

**Comment by WinnerWind** [comment]
Hi there! An update
When using Polybar scripts, it seems to me that something goes wrong and the applet bricks Budgie from starting properly, making it go into a vegetative state. 
I'll edit this message when I get more information.

1. It seems that most if not all of Polybar Scripts are affected, because of a bug that makes a crash the moment an external script is called.
2. Hi there! Upon even more testing, it seems that the plugin bricks the desktop if ANY input is given, literally anything. It just broke with this simple script. 
![image](https://github.com/szwsck/budgie-script-applet/assets/71366717/76148f54-eff2-4cd5-a294-9b66d29d61ad)
This makes the plugin unusable.

**Comment by heyeddi** [comment]
I just installed this, it works fine, I am running on EndeavorOS, Budgie verison 10.9.2

I tried installing for [AUR](https://aur.archlinux.org/packages/budgie-indicator-applet) and it does not work, installed it manually following the readme instructions. 
I am running a script that I used to run on polybar, it tells me what activitiy I am tracking on toggl track. 

![image](https://github.com/user-attachments/assets/6b436e0d-d06b-4e72-a164-f695bfaf854a)

Just wanted to leave an update here in case people find this issue

**Comment by WinnerWind** [comment]
@Bass-03 your comment gave me a wonderful idea.
For some reason, by default, file permissions are `-rw-r--r--` when installing manually, however after running `chmod +rwx *` on the directory, it works just fine. Not sure why I did not think of doing this, but I did. I wonder why `git` did not automatically fix file permissions like it always does. Well, can confirm, the plugin works now. Brilliant stuff! Will test and edit this message based on my findings now.
Note : new permissions are `-rwxr-xr-x`

Bad news : this still doesnt solve the freezing problem. The applet freezes the whole panel when anything other than a simple `echo` is given, which sucks. Command I gave was `zscroll -l 8 "$(playerctl metadata --format "{{title}} - {{artist}}")"`. Even `zscroll -l 8 abcdefghijklmnopqrstuv` failed. Stuff like `ls` and `time` work but give a blank output, but don't crash the panel. Only "Echo" works properly.
